module ErrorCodes
  RECORD_NOT_FOUND = "RECORD_NOT_FOUND".freeze
  VALIDATION_FAILED = "VALIDATION_FAILED".freeze
  PARAMETER_MISSING = "PARAMETER_MISSING".freeze
  CONFLICT = "CONFLICT".freeze
  UNAUTHORIZED = "UNAUTHORIZED".freeze
  FORBIDDEN = "FORBIDDEN".freeze
  RATE_LIMITED = "RATE_LIMITED".freeze
  INTERNAL_ERROR = "INTERNAL_ERROR".freeze
  UNPROCESSABLE = "UNPROCESSABLE_ENTITY".freeze
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED".freeze
end
