services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ribuzz_development
      RAILS_ENV: development
      JWT_SECRET: hackathon_dev_secret
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      WEBHOOK_SECRET: hackathon_webhook_secret_cambiar
      N8N_WEBHOOK_URL: https://n8n.srv1097452.hstgr.cloud/webhook/ribuzz-diagnostico
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/rails

volumes:
  pgdata:
