module ErrorCodes
  RECORD_NOT_FOUND = "NOT_FOUND"
  VALIDATION_FAILED = "VALIDATION_FAILED"
  PARAMETER_MISSING = "PARAMETER_MISSING"
  CONFLICT = "CONFLICT"
  UNAUTHORIZED = "UNAUTHORIZED"
  INTERNAL_ERROR = "INTERNAL_ERROR"
  INVALID_TRANSITION = "INVALID_TRANSITION"
  DUPLICATE_PLAN = "DUPLICATE_PLAN"
end